# Generated by Django 4.1.7 on 2023-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=200)),
                ('product_stock', models.IntegerField()),
                ('product_price', models.FloatField()),
            ],
            options={
                'db_table': 'addproducts',
            },
        ),
    ]
