# Generated by Django 4.1.7 on 2023-03-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_seller'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
    ]
