# Generated by Django 4.1.7 on 2023-03-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_seller'),
        ('seller', '0002_addproducts_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
    ]
