# Generated by Django 4.1.7 on 2023-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
