# Generated by Django 4.1.7 on 2023-03-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_c_password_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
