# Generated by Django 4.1.7 on 2023-03-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_email', models.CharField(max_length=50)),
                ('s_mobile', models.CharField(max_length=30)),
                ('s_password', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
